import {Selector} from 'testcafe';

export default class readKRV_shortTermTravelInsurance {

    constructor() {

        this.shortTermTravelInsurancePageHeader = Selector('h2.m-0.text-white.ng-scope[data-translate="label:short-term-travel-view"]')
        this.yourInsurance = Selector('h3.mb-2.d-inline-block.ng-scope[data-translate="heading:insurance"]')
        this.policyHolder = Selector('p.col-lg-3.details_label.ng-scope[data-translate="label:policy-holder-view"]')
        this.policyHolderName = Selector('p.policy-holder-name.col-lg-6')
        this.travelDates = Selector('p.col-lg-3.details_label.ng-scope[data-translate="label:travel-dates"]')
        this.travelDateValue = Selector('p.col-lg-9.ng-scope')
        this.whoIsInsuredLabel = Selector('p.col-lg-3.details_label.ng-scope[data-translate="question:insured-persons"]')
        this.firstInsuredPersonName = Selector('span.insured-person-name.ng-binding').nth(0)
        this.secondInsuredPersonName = Selector('span.insured-person-name.ng-binding').nth(1)
        this.firstPersonDateOfBirth = Selector('p.mb-0.insurance-details__dob.ng-binding').nth(0)
        this.secondPersonDateOfBirth = Selector('p.mb-0.insurance-details__dob.ng-binding').nth(1)
        this.cover = Selector('p.col-lg-3.details_label.ng-scope[data-translate="label:coverage"]')
        this.coverValue = Selector('span.ng-binding').nth(3)
        this.coverArea = Selector('p.col-lg-3.details_label.ng-scope[data-translate="label:coverage-area"]')
        this.coverAreaValue = Selector('span.ng-binding').nth(4)
        this.yourPolicy = Selector('p.col-lg-3.details_label.ng-scope[data-translate="label:policy"]')
        this.policyDocumentLink = Selector('a.icon-link.ng-scope').nth(0)
        this.oneOffPremium = Selector('p.col-lg-3.details_label.ng-scope[data-translate="label:premium"]')
        this.oneOffPremiumValue = Selector('p.mb-1.ng-binding')
        this.policyDisclaimer = Selector('p.ng-scope[data-translate="message:policy-sheet"]')
        this.winterAndUnderwaterCover = Selector('p.col-lg-3.details_label.ng-scope[data-translate="Winter and underwater sports cover"]')
        this.winterAndUnderwaterCoverValue = Selector('span.ng-binding').nth(7)
        this.cancellationInsurance = Selector('p.col-lg-3.details_label.ng-scope[data-translate="Cancellation insurance"]')
        this.cancellationInsuranceValue = Selector('span.ng-binding').nth(10)
        this.bookingDate = Selector('p.col-lg-3.details_label.ng-scope[data-translate="Booking Date"]')
        this.bookingDateValue = Selector('p.col-lg-3.ng-binding').nth(0)
        this.tripCost = Selector('p.col-lg-3.details_label.ng-scope[data-translate="Trip cost"]')
        this.tripCostValue = Selector('p.col-lg-3.ng-binding')
        this.additionalCoverPolicyText = Selector('p.ng-scope[data-translate="Check your policy or the terms and conditions for the details of your additional cover."]')
        this.changingYourInsurance = Selector('h3.mt-5.mb-2.pl-2.pr-2.p-sm-0.ng-scope[data-translate="heading:insurance-change"]')
        this.changingYourInsuranceValue = Selector('p.mb-4.pl-2.pr-2.p-sm-0.ng-scope[data-translate="message:insurance-change-text"]')
        this.policyDetails = Selector('h3.mb-2.ng-scope[data-translate="heading:policy-details"]')
        this.policyNumber = Selector('p.col-lg-3.details_label.ng-scope[data-translate="label:policy-number"]')
        this.policyNumberValue = Selector('p.col-lg-3.ng-binding').nth(2)
        this.requestDate = Selector('p.col-lg-3.details_label.ng-scope[data-translate="label:application-date"]')
        this.requestDateValue = Selector('p.col-lg-3.ng-binding').nth(3)
        this.termsAndConditions = Selector('p.col-lg-3.details_label.ng-scope[data-translate="label:requirement"]')
        this.termsAndConditionsLink = Selector('a.icon-link.ng-scope[data-translate="pdf:condition"]')
        this.accountNumber = Selector('p.col-lg-3.details_label.ng-scope[data-translate="label:account-number"]')
        this.accountNumberValue = Selector('p.col-lg-6.ng-binding')
        this.cancellingYourInsurance = Selector('h3.mt-5.mb-2.pl-2.pr-2.p-sm-0.ng-scope[data-translate="heading:cancel-insurance"]')
        this.cancellingYourInsuranceText = Selector('p.mb-2.col-lg-11.pl-2.pr-2.p-sm-0.ng-scope[data-translate="message:cancel-insurance"]')
        this.submitClaim = Selector('button#short-term-travel-view-submit')
        this.myProducts = Selector('span.smb-1.sml-1.text-white.product-heading.ng-scope[data-translate="label:products"]')
        this.cancelInsuranceLink = Selector('span.ng-scope[data-translate="text:cancel-insurance"]')
    }
}